### ISSUE TITLE
Proposal: Have DeepLinkDispatch supply its Proguard Rules

### ISSUE THREAD

**Issue by MinceMan** [airbnb/DeepLinkDispatch#107]
In a build.gradle we can have the deeplinkdepatch point to its own proguard rules like such.
```groovy
android {
  defaultConfig {
    consumerProguardFiles 'consumer-proguard-rules.pro'
  }
}
```

This would require turning deeplinkdepatch into an android library project. Would this be something of interest or should this remain a java module?

**Comment by felipecsl** [comment]
We don't have plans to convert it into an Android library for now, but thanks for your proposal!
