### ISSUE TITLE
Stale example code for Callbacks in Readme

### ISSUE THREAD

**Issue by Saketme** [airbnb/DeepLinkDispatch#113]
The example code for registering a `BroadcastReceiver` for listening to deeplinks uses stale constants. For instance, `DeepLinkActivity.EXTRA_URI`, `DeepLinkActivity.EXTRA_SUCCESSFUL`, etc., have all been replaced by `DeepLinkHandler.EXTRA_URI` and `DeepLinkHandler.EXTRA_SUCCESSFUL` and so on in v2.0.1

**Comment by felipecsl** [comment]
Fixed in #116
