### ISSUE TITLE
path matching problem

### ISSUE THREAD

**Issue by Arash-gm** [airbnb/DeepLinkDispatch#114]
i'm deeplinking two urls this way : 

    @DeepLink({"myapp://st/path/selective/",
        ,"myapp://st/path/{destination}"
        })

the problem is when i test these with "myapp://st/path/selective" without "/" character , it matches the second path and use selective as {destination} . how can i use first path even i don't put "/" at the end of the link?

**Comment by felipecsl** [comment]
You can't. You'll have to use a single path, just `"myapp://st/path/{destination}"` and match the `destination` parameter manually
