### ISSUE TITLE
null check of intent data in DeepLinkDelegate

### ISSUE THREAD

**Issue by iveyalkin** [airbnb/DeepLinkDispatch#115]
Method `DeepLinkDelegate.dispatchFrom`
```
...
Uri uri = sourceIntent.getData();
if (uri == null) {
  return createResultAndNotify(activity, false, null, "No Uri in given activity's intent.");
}
...
```
If the data URI is `null` somehow, then `createResultAndNotify` is getting called with `null` URL argument which leads to an NPE later on in `DeepLinkDelegate.notifyListener`.
```
...
intent.putExtra(DeepLinkHandler.EXTRA_URI, uri.toString());
...
```

**Comment by felipecsl** [comment]
Good point. Since `Uri` is `Parcelable`, we should be able to just put it directly into the `Bundle` without the need to call `toString()`. Fix coming

**Comment by felipecsl** [comment]
Oh, this has been [fixed on master already](https://github.com/airbnb/DeepLinkDispatch/blob/master/deeplinkdispatch-processor/src/main/java/com/airbnb/deeplinkdispatch/DeepLinkProcessor.java#L283-L284). Closing
