### ISSUE TITLE
Error:(42, 0) Gradle DSL method not found: 'apt()'

### ISSUE THREAD

**Issue by hishamBakr** [airbnb/DeepLinkDispatch#12]
Dear,
     when I add
compile 'com.airbnb:deeplinkdispatch:1.1.0'
    apt 'com.airbnb:deeplinkdispatch-processor:1.1.0'

to gradle file, I face this error:
Error:(42, 0) Gradle DSL method not found: 'apt()'

I use gradle: 
   classpath 'com.android.tools.build:gradle:1.2.3'

Please advise.

**Comment by hishamBakr** [comment]
After investigation, I fixed the issue by adding
 classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'

this was not mentioned in instalation guide

**Comment by felipecsl** [comment]
good point, we should add this to the readme. thanks!
