### ISSUE TITLE
URL conflict

### ISSUE THREAD

**Issue by MostafaDavodi** [airbnb/DeepLinkDispatch#130]
i have 3 links like this : 
1. @DeepLink("http://example.com/index.php?page=share&type=type3&id={id}")
2. @DeepLink("http://example.com/index.php?page=share&type=type2&id={id}")
3. @DeepLink("http://example.com/index.php?page=share&type=type1&id={id}")

and for each of them i have an activity as a host : 
1. ActivityA
2. ActivityB
3. ActivityC

but when i have links for urls 2 it bring up activityA as a host so we can not load UI correctly for it. 
i do not know why it confuse host activity. but when i alter URL for second path to something completely different from others URL (http://example.com/index.php/type2/{id}), correctly bring up ActivityB.

**Comment by felipecsl** [comment]
URI interpolation in the query parameters is not currently supported, only on the path component.
