### ISSUE TITLE
Parameters can't have '_' and '-' symbols, but should

### ISSUE THREAD

**Issue by Javernaut** [airbnb/DeepLinkDispatch#14]
I was about to use your library in my project, but it didn't recognize my url. As was found out, the regexp for parameters is too restrictive, as it forbids _ and - symbols.

My target url was like this:
someschema://somepath/an-identifier-with-dashes

Please, add this functionality.

**Comment by MichaelEvans** [comment]
@felipecsl @cdeonier is there any reason that the param value regex is so restrictive? I would like to use hyphenated slugs in my paths as well. (I can put up a PR with a test if there's no real reason)

**Comment by cdeonier** [comment]
@Javernaut @MichaelEvans Just an oversight. We should allow those symbols in the parameter. I'll go ahead and add this in.

**Comment by cdeonier** [comment]
Oh, you've got it up already, great. I'll review that.
