### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Yanqilong** [airbnb/DeepLinkDispatch#140]
sample-library missing LibraryDeepLinkModuleLoader.java

**Comment by MichaelEvans** [comment]
@Yanqilong That file is generated by the annotation processor during compilation.

(If you're curious, you can find the generated class under `build/generated/source/apt/<VARIANT>/`)

**Comment by felipecsl** [comment]
What Mike said :)

**Comment by Yanqilong** [comment]
ths, MichaelEvans

**Comment by Yanqilong** [comment]
Can I ask some questions?  In that case,  If between App project(main project) and library project(sub project) not exist dependency, I will use DeepLinkDispatch from main project jump to sub project,  Can I do it?

**Comment by felipecsl** [comment]
No, there needs to be a dependency between the projects, otherwise project A cannot see classes from project B

**Comment by Yanqilong** [comment]
I`am very said,  I want to component development, every component  is independent, there has a problem, how to communicate to between component ?  If DeepLinkDispatch as a bridge(like a router or event bus) implement component communicate when it not exist dependency, it is very nice.

**Comment by felipecsl** [comment]
Well I'm not sure what you mean then. if you have an Android app that uses a library project, you need to have a dependency from your app to your library, like `compile project(:library)` otherwise the library simply won't be included in your app at all. They can still be "independent" though.
