### ISSUE TITLE
matching algorithm for same scheme, host and different path.

### ISSUE THREAD

**Issue by iam1492** [airbnb/DeepLinkDispatch#141]
I want to know the reason why library use regex matching with scheme, host and path set.
Why not just matchnig the scheme, host. (than we can parsing the rest things from code)
For me, I want use scheme something like 
1 ."myscheme://myhost/mypath/mypath2" 
2. "myscheme://myhost/mypath3/mypath4"

with one deeplink 
@DeepLink(myscheme://myhost") 

then I can parse path from Uri. (something like uri.getPath())
I don't want to do
@DeepLink({"myscheme://myhost/mypath/mypath2", "myscheme://myhost/mypath3/mypath4"}) 

I got error from broadcast receiver when using @DeepLink(towneers.alpha://web") 
"Error deep linking: towneers.alpha://web/wv/articles/hot with error message + No registered entity to handle deep link: towneers.alpha://web/wv/articles/hot"

Is there any solution or workaround to do what I want with current library version?
or Do you think it is good approach that I just use broadcast receiver to take care of only this case?

**Comment by felipecsl** [comment]
What you want is a catchall (wildcard) deep link. DeepLinkDispatch wasn't really designed for this scenario. This is a lot more simple and you could handle this by using a simple intent-filter in your manifest and that's it. You don't need DeepLinkDispatch for that.

**Comment by iam1492** [comment]
@felipecsl I mean not all the deep link but want catch same scheme and host (not path)
There can be multiple hosts. 
If I want to add more intent filter with my scheme with host then it is duplicate with Airbnb deeplinkActivity's scheme(event if it has no host) so two choices of same my app shown when clicking the link.

What I meant was that I don't want to add many many schemes such as:
@DeepLink({"myscheme://myhost/mypath/mypath2", "myscheme://myhost/mypath3/mypath4",
"myscheme://myhost/mypath5/mypath6", "myscheme://myhost/mypath7/mypath8", "myscheme://myhost/mypath9/mypath10"})

For example, if uri "myscheme://myhost/mypath/mypath2" dilivered then libaray can first detect scheme + host + path first and If not matched then detect only scheme + host. 
In this way, developer can do rest of thing and also server can add new target uri dynamically.

Anyway I cannot add more intent filter because it has same scheme with deeplinkActivity.
