### ISSUE TITLE
Deep link documentation generation

### ISSUE THREAD

**Issue by kxfang** [airbnb/DeepLinkDispatch#142]
Hi, would there be any interest in supporting a gradle task that generates documentation containing all deep links supported by a project? The task could potentially pick up javadoc above any @DeepLink annotations and use those as the description for the links.

**Comment by felipecsl** [comment]
Hey @kxfang thanks for asking! Yes, I think that'd be a valuable addition. Is that something you're planning to contribute? That'd be great.

**Comment by kxfang** [comment]
@MichaelEvans has bravely volunteered to look into this

**Comment by mapyo** [comment]
ref. https://github.com/hisaichi5518/DeepLinkDispatchDocumentor
