### ISSUE TITLE
Access to the original intent data string

### ISSUE THREAD

**Issue by fernandospr** [airbnb/DeepLinkDispatch#145]
I need to get the original data string from the intent that launched my activities with a deeplink. Normally, I would do this by calling `getIntent().getDataString()` in my activity's `onCreate`, however, because I'm using this library I can't do it that way anymore, because there is a single point of entry (which is the `DeepLinkActivity`). So, I no longer know where to get this data.

Should I create a `CustomDeepLinkActivity` that inherits from `DeepLinkActivity` to do this and override `onCreate`? By checking your source code, I don't think it would be an option, because you call `finish()` internally, so I guess my code would not be called.

Note: I have to do this because I'm integrating a [tool](https://support.appsflyer.com/hc/en-us/articles/207032126-AppsFlyer-SDK-Integration-Android#section_5.6) that tracks the deeplinks for re-targeting attribution, and by looking at its source code I saw they are calling `activity.getIntent().getDataString()` internally. They expect to have each activity registered in the manifest with an intent-filter and call the sdk on each activity's `onCreate`.

Thanks.

**Comment by felipecsl** [comment]
You can use `getIntent().getStringExtra(DeepLink.URI)` to obtain the original data URI that launched your app.
By the way, starting with version 3.0.0-rc1, DeepLinkDispatch no longer generates a `DeepLinkActivity` for you. You have to manually call `DeepLinkDelegate#dispatchFrom()`.
That means you have complete access to the original intent and can do whatever you want with it :)
Check the sample app in the repository for an example!

**Comment by fernandospr** [comment]
Thanks @felipecsl.

Unfortunately, the SDK library that that tracks the deeplinks exposes this method:
`AppsFlyerLib.getInstance().sendDeepLinkData(activity)` which internally calls `activity.getIntent().getDataString()` so I won't be able to use `getIntent().getStringExtra(DeepLink.URI)`. 

I hope I can do this with the 3.0.0-rc1 version.
