### ISSUE TITLE
Support for Kotlin

### ISSUE THREAD

**Issue by bubunyo** [airbnb/DeepLinkDispatch#153]
How do integrate this library with a kotlin project.

**Comment by felipecsl** [comment]
It shouldn't matter whether you're using it on a Java or Kotlin project, as long as the annotation processor runs, it should work the same way.

**Comment by renannery** [comment]
@bubunyo It might be useful for you. In your `build.gradle` instead of `annotationProcessor 'com.airbnb:deeplinkdispatch-processor:3.1.0'` use `kapt "com.airbnb:deeplinkdispatch-processor:3.1.0"`
