### ISSUE TITLE
Deeplink from browser not working

### ISSUE THREAD

**Issue by nilesh1433** [airbnb/DeepLinkDispatch#154]
Hi
I have integrated my app with this version number 'com.airbnb:deeplinkdispatch:3.0.0-rc2'  . Deeplink works when triggered through adb but does not work when same link is opened in browser.

Here is my Manifest declaration:-
```
<activity
            android:name=".deeplink.DeepLinkDelegateActivity"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="https" />
                <data android:host="m.<my_site>.in"/>
            </intent-filter>
</activity>
```
Please let me know, if am missing anything.

Note:- I have not selected any default app to open the link.

**Comment by nilesh1433** [comment]
Hi Guys,
Need solution on urgent basis. It would be great if someone helps me out.

**Comment by alexfu** [comment]
@nilesh1433 Your `data` tag format is incomplete. You're using **two** data tags, each having what the other is missing. You need to have both `scheme` and `host` in the data tag. https://developer.android.com/guide/topics/manifest/data-element.html

**Comment by nilesh1433** [comment]
@alexfu  Hi i forgot to update the code while posting. I did tried with putting host in same data tag, but with no success. It works only when i specify path with it.

```<activity
            android:name=".deeplink.DeepLinkDelegateActivity"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="https"
                    android:host="<mysite>"/>
            </intent-filter>
        </activity>```

**Comment by alexfu** [comment]
@nilesh1433 can you post the full `adb` command you were using that worked. also, providing the deep link URLs you're using in the `@DeepLink` annotation would be helpful.

**Comment by nilesh1433** [comment]
@alexfu  - 

Adb command
adb shell am start -W -a android.intent.action.VIEW -d "https://<my_site>/offers"

@DeepLink("https://<my_site>/offers")
```
public final class MyModuleLoader implements Parser {
  private static final List<DeepLinkEntry> REGISTRY = Arrays.asList(
    new DeepLinkEntry("https://<my_site>/offers", DeepLinkEntry.Type.CLASS, DeepLinkingActivity.class, null)
  );

  @Override
  public DeepLinkEntry parseUri(String uri) {
    for (DeepLinkEntry entry : REGISTRY) {
      if (entry.matches(uri)) {
        return entry;
      }
    }
    return null;
  }
}
```

**Comment by alexfu** [comment]
@nilesh1433 looks fine to me. when you say 

> does not work when same link is opened in browser

can you clarify? do you mean:

1. when you type `https://<my_site>/offers` into the browser address bar?
2. when you click on a link tag (`<a>`) in the browser that points to `https://<my_site>/offers`?

If you mean 1, then deep linking won't work because the browser is consuming the URL, not the OS.

**Comment by nilesh1433** [comment]
@alexfu 

It is 2nd case. My site has a offer section. On clicking of this, it gets redirected to /offers.

**Comment by alexfu** [comment]
@nilesh1433 it might be that the link tag is referencing `/offers` instead of the full URL. not sure if that would make a difference but you can test it by using the full URL.

**Comment by nilesh1433** [comment]
@alexfu Can i have your email? I can share more details over email.

**Comment by alexfu** [comment]
@nilesh1433 lets keep the conversation here in case other people have a similar problem.

**Comment by nilesh1433** [comment]
@alexfu Nope not working with full url also. Anything elese which i should look for.

**Comment by alexfu** [comment]
@nilesh1433 seems I was wrong about your original `data` tags. 

```
<intent-filter . . . >
    <data android:scheme="something" />
    <data android:host="project.example.com" />
    . . .
</intent-filter>
```

is the same as

```
<intent-filter . . . >
    <data android:scheme="something" android:host="project.example.com" />
    . . .
</intent-filter>
```

sorry for that. only thing i think of is to make sure the scheme matches up everywhere. make sure that the link you're clicking on in the browser isn't `http` when you want to match on `https`.

**Comment by pkliang** [comment]
In my case, `pathPrefix` also needs to be set, otherwise it won't work.

**Comment by felipecsl** [comment]
Seems like there isn't a DeepLinkDispatch issue here? Feel free to reopen otherwise.

**Comment by mochadwi** [comment]
The deeplink also not working for native browser (default browser from android) and chrome custom

@felipecsl @alexfu @nilesh1433

**Comment by rakanugroho** [comment]
> it will work, if the link pasted in Default Google search, but not working in any other browsers.

if you want to access deeplink from google Chrome or google tabs, you must to use standard template like
`intent://payment?id=100#Intent;scheme=privyid;package=com.grab.android;action=android.intent.action.VIEW;end”`

for detail please check this issue https://developer.chrome.com/multidevice/android/intents
