### ISSUE TITLE
Ordering of entries in registry

### ISSUE THREAD

**Issue by dlackty** [airbnb/DeepLinkDispatch#160]
For our use cases:

* `/recipes/popular` leads to a list activity
* `/recipes/:id` leads to a single recipe activity

If we annotate two methods with both deep links, we hope the loader can first match `popular` instead of `:id`. There might be other use cases like: `/recipes/:id` v.s. `/recipes/search?q={}`

(Actually we use all of these at the same time)

Possible approach to solve this problem:

1. Add an order parameter for annotation
2. Allow custom loader #159 

Please advice, and I would definitely like to help implement a solution.

**Comment by felipecsl** [comment]
Fixed via #171
