### ISSUE TITLE
How to get the Array of Annotated Deep Link URIs?

### ISSUE THREAD

**Issue by BrunoVillanova** [airbnb/DeepLinkDispatch#164]
Hi,

I need to get a list containing all annotated Deep Link URIs.
Is there any way to achieve this?
I can see that it exists on Loader generated class, but private.

Thanks.

**Comment by felipecsl** [comment]
Sure we can make the `REGISTRY` public.

**Comment by BrunoVillanova** [comment]
👍🏻

**Comment by felipecsl** [comment]
I've just published DLD v3 final with this change

**Comment by BrunoVillanova** [comment]
Thanks, Felipe!
