### ISSUE TITLE
Activity between ParseDeepLink Activity and First Activity (e.g Splash)

### ISSUE THREAD

**Issue by Diego-Franco** [airbnb/DeepLinkDispatch#172]
i have a question about your library, i'm thinking to use this, but i want to know if is possible to support something like this

**SplashActivity -> CodeActivity -> ParseActivity**

is possible to use this library if i have something like this, the thing is, no matters what, the CodeActivity always is the first activity the user watch. 

can you resolve this question please?

**Comment by felipecsl** [comment]
Yes, you can arrange it however you want. Just annotate your code Activity and handle the deep link as you see fit.

**Comment by Diego-Franco** [comment]
maybe my question was not good to read.

in this case the CodeActivity doesn't have any deep link so this don't need a annotation, for this the **CodeActivity** always is displayed before to show the others screens, e.g if you press **Home button** or if you click on **Recent activities** and you get a deep link the first screen you will see is the **CodeActivity**

**Comment by felipecsl** [comment]
For that you can use `android:parentActivityName` in your `AndroidManifest.xml`
