### ISSUE TITLE
Unexpected behavior when opening deep links from Google Apps?

### ISSUE THREAD

**Issue by ivamluz** [airbnb/DeepLinkDispatch#175]
We are facing a scenario that feels like an unexpected one.

In order to reproduce this error, I've modified the sample app a bit in order to navigate from CustomPrefixesActivity to MainActivity. You can check it out from [here](https://github.com/ivamluz/DeepLinkDispatch/tree/googleapps).

With this modified sample app, here are the steps to reproduce:

1. Send through Gmail a deep link that the sample app can handle (http://airbnb.com/user/1234, for example);
2. Click the deep link on Gmail app;
3. Sample app will be properly opened on CustomPrefixesActivity;
4. Click "Launch main activity" button;
5. Keep the sample app opened and get back go Gmail app;
6. Click the deep link sent by email again;
7. Sample app is shown again, but instead of opening on CustomPrefixesActivity, it keeps showing MainActivity.

It doesn't seem like an intent is triggered with the deep link extras.

Is this an expected behavior? Doesn't anybody have an idea of how to make CustomPrefixesActivity to be opened again in this scenario?

**Comment by ivamluz** [comment]
Found out that adding `android:launchMode="singleTask"` to DeepLinkActivity makes it work as expected, but I'm still unsure about the side effects it may cause.

**Comment by felipecsl** [comment]
That's an expected behavior. You have to handle task reordering yourself. It's not something that DeepLinkDispatch handles.
