### ISSUE TITLE
DeepLinkHandler trouble me

### ISSUE THREAD

**Issue by InLook** [airbnb/DeepLinkDispatch#177]
Now I dev  router sdk, I find some thing :
`To solve register sub module deep link by **DeepLinkHandler**.But if sub module is too much. it is trouble. `
I find other way, sub module register by yourself,But This problem is

>  in main module,How can  apt generate class  which manage every sub module generate class.

Waiting for your Help,Thank You
PS：Sorry，Forgive my poor English，My opinion may be clear

**Comment by felipecsl** [comment]
I'm sorry I can't understand your problem 😢 
Please try rephrasing it. Going through Google Translate might help!
