### ISSUE TITLE
iOS equivalent?

### ISSUE THREAD

**Issue by Shivam101** [airbnb/DeepLinkDispatch#178]
Hello,

I am looking to implement dynamic deeplinks such as the one supported by DeeplinkDispatch in my iOS app as well. Is there an iOS equivalent for this library? Or any other way I can go about implementing this in iOS? Specifically, I would like my deeplinks to be able to route to any screen in the app on the basis of class name.

Thanks!

**Comment by dudego** [comment]
Hi,
I've made a small project that does this in a similar way. Check this [DeepLinkHandler](https://github.com/dudego/DeepLinkHandler). Hope this helps
Cheers

**Comment by ivela** [comment]
I use this and works very nice: https://github.com/joeldev/JLRoutes
