### ISSUE TITLE
Android-apt incompatible with the newest versions of libraries/build tools

### ISSUE THREAD

**Issue by carlosrivin** [airbnb/DeepLinkDispatch#184]
Trying to build a project that with the latests tools now gives us this warning:

> Warning:android-apt plugin is incompatible with future version of Android Gradle plugin.  Please use 'annotationProcessor' configuration instead.

It also crashes during build with this message:

`Error:Error converting bytecode to dex:
Cause: invokedynamic not supported
Error:com.android.dx.cf.code.SimException: invokedynamic not supported
Error:	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
Error:	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
Error:	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
Error:	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
Error:	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
Error:	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
Error:	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
Error:	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
Error:	at com.android.builder.dexing.DexArchiveBuilder.processOutputs(DexArchiveBuilder.java:110)
Error:	at com.android.builder.dexing.DexArchiveBuilder.convert(DexArchiveBuilder.java:91)
Error:	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.lambda$cacheMissAction$0(DexArchiveBuilderTransformCallable.java:236)
Error:	at com.android.builder.utils.FileCache.lambda$createFile$1(FileCache.java:260)
Error:	at com.android.builder.utils.FileCache.lambda$null$5(FileCache.java:443)
Error:	at com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)
Error:	at com.android.builder.utils.SynchronizedFile.write(SynchronizedFile.java:232)
Error:	at com.android.builder.utils.FileCache.lambda$queryCacheEntry$6(FileCache.java:415)
Error:	at com.android.builder.utils.SynchronizedFile.doActionWithMultiProcessLocking(SynchronizedFile.java:265)
Error:	at com.android.builder.utils.SynchronizedFile.read(SynchronizedFile.java:215)
Error:	at com.android.builder.utils.FileCache.queryCacheEntry(FileCache.java:391)
Error:	at com.android.builder.utils.FileCache.createFile(FileCache.java:273)
Error:	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.getFromCacheAndCreateIfMissing(DexArchiveBuilderTransformCallable.java:185)
Error:	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:147)
Error:	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransformCallable.call(DexArchiveBuilderTransformCallable.java:53)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Caused by: com.android.dx.cf.code.SimException: invokedynamic not supported
Error:	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:810)
Error:	at com.android.dx.cf.code.BytecodeArray.processWorkSet(BytecodeArray.java:162)
Error:	at com.android.dx.cf.code.BasicBlocker.doit(BasicBlocker.java:346)
Error:	at com.android.dx.cf.code.BasicBlocker.identifyBlocks(BasicBlocker.java:81)
Error:	at com.android.dx.cf.code.Ropper.<init>(Ropper.java:380)
Error:	at com.android.dx.cf.code.Ropper.convert(Ropper.java:349)
Error:	at com.android.dx.dex.cf.CfTranslator.processMethods(CfTranslator.java:285)
Error:	at com.android.dx.dex.cf.CfTranslator.translate0(CfTranslator.java:141)
Error:	at com.android.dx.dex.cf.CfTranslator.translate(CfTranslator.java:95)
Error:	at com.android.builder.dexing.DexArchiveBuilderCallable.translateClass(DexArchiveBuilderCallable.java:93)
Error:	at com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:74)
Error:	at com.android.builder.dexing.DexArchiveBuilderCallable.call(DexArchiveBuilderCallable.java:43)
Error:	... 5 more
Error:Caused by: com.android.dx.cf.iface.ParseException: invokedynamic not supported
Error:	at com.android.dx.cf.code.BytecodeArray.parseInstruction(BytecodeArray.java:777)
Error:	... 16 more
Error:...at bytecode offset 0000000b
Error:...while working on method removeIf:(Ljava/util/function/Predicate;)Z
Error:...while processing removeIf (Ljava/util/function/Predicate;)Z
Error:...while processing com/google/common/collect/Lists$TransformingSequentialList.class`

Do you guys have any plan of updating the library to make this work?

**Comment by felipecsl** [comment]
@carlosrivin you shouldn't be using `android-apt` anymore with the latest Android Gradle Plugin versions. 
The project README instructions have been already updated a while ago to reflect this:
https://github.com/airbnb/DeepLinkDispatch#usage
