### ISSUE TITLE
Gradle. Conflics.

### ISSUE THREAD

**Issue by Sar777** [airbnb/DeepLinkDispatch#185]
Hi,  i have an error with build gradle

```
Error:Conflict with dependency 'com.google.code.findbugs:jsr305' in project ':app'. Resolved versions for app (3.0.1) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.
```

Andriod Studio 2.3.3
Gradle 2.3.3

what a problem? thx.

**Comment by felipecsl** [comment]
This is not an issue with DeepLinkDispatch.
You can easily work around the conflict by adding the correct jsr305 version as a test dependency:
`androidTestCompile 'com.google.code.findbugs:jsr305:3.0.1`
