### ISSUE TITLE
Proguard removing DLD methods

### ISSUE THREAD

**Issue by SiavashB** [airbnb/DeepLinkDispatch#186]
I am using the `@DeepLink` annotation on a method as such

```
@DeepLink("https://www.example.com/news/v2/entries/{id}")
    public static TaskStackBuilder intentForTaskStackBuilderMethods(Context context) {
}
```

I have this in my proguard rules, as indicated by your instructions:

```
-keep class com.airbnb.deeplinkdispatch.** { *; }
-keepclasseswithmembers class * {
     @com.airbnb.deeplinkdispatch.DeepLink <methods>;
}
```

but proguard still removes my `intentForTaskStackBuilderMethods`

the only way I was able to get it to work was by adding the `@Keep` annotation above the method.

It seems as if the proguard rule you have noted in your readme, only protects the **class** containing the annotated methods, but not the methods itself

**Comment by seerazz** [comment]
@SiavashB i have the same problem too, adding the `@Keep` annotation on the method solve the problem

**Comment by felipecsl** [comment]
This is something that needs to be addressed by consumer applications, the library's Proguard settings won't be able to account for Activity annotated methods.
