### ISSUE TITLE
Pass in the full source URL template into receiver's intent extras

### ISSUE THREAD

**Issue by felipecsl** [airbnb/DeepLinkDispatch#187]
For any `@DeepLink` annotation, we need to pass in the original URL template into the Intent extras of the receiver, so they know which deep link was triggered.
In this case, `com.airbnb.deeplinkdispatch.EXTRA_URI` is not useful since it can't be used for aggregation purposes. That's because any variables in the original URL template would be already replaced with actual values.
Eg.:
* `@DeepLink("http://foo/bar")` => "http://foo/bar"
* `@DeepLink("http://foo/bar/{id}")` => "http://foo/bar/{id}"
* `@DeepLink({"blah://foo/{test}", "blah://baz/{test}"})` => Either "blah://foo/{test}" or "blah://baz/{test}", depending on which one got triggered.

**Comment by rossbacher** [comment]
Has been fixed by https://github.com/airbnb/DeepLinkDispatch/pull/229
