### ISSUE TITLE
Include host example in the usage doc

### ISSUE THREAD

**Issue by bblia** [airbnb/DeepLinkDispatch#188]
![image](https://user-images.githubusercontent.com/4870878/29050208-5b297102-7b8f-11e7-8132-5af1410de394.png)

In this section of the usage docs, it would be helpful to include an intent filter example with a specified host. I couldn't figure out why my stuff wasn't working until I went through the example and found the correct usage in the manifest file:

https://github.com/airbnb/DeepLinkDispatch/blob/14ebf3eaabb9098366c987f103ab8b1015fce7e6/sample/src/main/AndroidManifest.xml#L50

not a huge deal, but it could be useful for others who fall down the same hole as me :) Thanks for this lib!!

**Comment by felipecsl** [comment]
@bblia a host shouldn't be necessary in order for the deep linking to work. 
You can see there is an example with the `dld` scheme where the host is not specified: 
https://github.com/airbnb/DeepLinkDispatch/blob/14ebf3eaabb9098366c987f103ab8b1015fce7e6/sample/src/main/AndroidManifest.xml#L41

**Comment by felipecsl** [comment]
Also some unit tests that verify it works:
https://github.com/airbnb/DeepLinkDispatch/blob/fb53d23dea6f563d50e79e861d68d247dd1f5bfa/sample/src/test/java/com/airbnb/deeplinkdispatch/sample/MainActivityTest.java#L28-L81

**Comment by bblia** [comment]
is it not necessary for the https scheme? i had to add the host for it to work.

**Comment by felipecsl** [comment]
nope, the host is not necessary. just the scheme should suffice

**Comment by bblia** [comment]
I'm at a loss then, because removing it stops functionality on my end. It's included in all the intents with the http/https scheme in the sample app as well...

**Comment by bblia** [comment]
P.S. those tests are for a custom scheme, not http/https

**Comment by felipecsl** [comment]
@bblia ah, maybe that's why. It shouldn't matter whether the intent is custom or http/https, but that may be handled by a different application (chrome, for example) and maybe why your app is not receiving the deep link.
You can add a broadcast receiver and see if it receives any events of handled/unhandled deep links. if your broadcast receiver doesnt get called, it means that the intent didn't get routed to your app at all!

**Comment by bblia** [comment]
Yep, it wasn't getting routed / triggering the receiver without the host :)
it would just go straight to Chrome.
