### ISSUE TITLE
Activity Dispatcher Hook

### ISSUE THREAD

**Issue by cesards** [airbnb/DeepLinkDispatch#190]
Hi guys! 

First of all, congratulations and very good job!! This library is really awesome! It should be a must for all apps 🍻 .

I'm using the library as a default navigator for my app, but I've realised there is a case scenario not covered at all. The possibility of having an activity hook, in order to add navigation options like `activity.startActivityForResult` or even adding activity transitions.

I had a look to the documentation and I've been having a look at the opened/closed issues and I haven't found anything related to Activity dispatcher hook. 

There is a way to hook Intents:

> You can also annotate any public static method with @DeepLink. DeepLinkDispatch will call that method to create the Intent and will use it when starting your Activity via that registered deep link:

```
@DeepLink("foo://example.com/methodDeepLink/{param1}")
public static Intent intentForDeepLinkMethod(Context context) {
  return new Intent(context, MainActivity.class)
      .setAction(ACTION_DEEP_LINK_METHOD);
}
```

or even customising the `Activity` backstack:
```
@DeepLink("http://example.com/deepLink/{id}/{name}")
public static TaskStackBuilder intentForTaskStackBuilderMethods(Context context) {
  Intent detailsIntent =  new Intent(context, SecondActivity.class).setAction(ACTION_DEEP_LINK_COMPLEX);
  ...
  taskStackBuilder.addNextIntent(detailsIntent);
  return taskStackBuilder;
}
```

But there is no way of retrieving the Activity context. 

Most of the logic is [here](https://github.com/airbnb/DeepLinkDispatch/blob/master/deeplinkdispatch-processor/src/main/java/com/airbnb/deeplinkdispatch/DeepLinkProcessor.java). As far as I see, I guess, casting the [Context](https://github.com/airbnb/DeepLinkDispatch/blob/c9a89befd4c03469bfa870ecba17758ff96dbdf6/deeplinkdispatch-processor/src/main/java/com/airbnb/deeplinkdispatch/DeepLinkProcessor.java#L80) you are getting from the class via reflection would be enough? But we still need a hook, don't we?

**Comment by cesards** [comment]
Related to what I said about the Context, I just realised it's not actually a cast, we are using the `DeepLinkHandler` Activity proxy [approach](https://github.com/airbnb/DeepLinkDispatch/blob/fb53d23dea6f563d50e79e861d68d247dd1f5bfa/deeplinkdispatch-processor/src/test/resources/DeepLinkDelegate.java), so I guess what I'm asking for would be somehow possible?

```
@DeepLinkHandler({ AppDeepLinkModule.class, LibraryDeepLinkModule.class })
public class DeepLinkActivity extends Activity {
  @Override protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // DeepLinkDelegate, LibraryDeepLinkModuleLoader and AppDeepLinkModuleLoader
    // are generated at compile-time.
    DeepLinkDelegate deepLinkDelegate = 
        new DeepLinkDelegate(new AppDeepLinkModuleLoader(), new LibraryDeepLinkModuleLoader());
    // Delegate the deep link handling to DeepLinkDispatch. 
    // It will start the correct Activity based on the incoming Intent URI
    deepLinkDelegate.dispatchFrom(this);
    // Finish this Activity since the correct one has been just started
    finish();
  }
```

**Comment by felipecsl** [comment]
Hi Cesar!

If I understood correctly, what you want is already possible. When your `public static` method annotated with `@DeepLink` is called, the `Context` parameter is actually an `Activity`, so it's safe to just cast it like below:
```java
@DeepLink("foo://example.com/methodDeepLink/{param1}")
public static Intent intentForDeepLinkMethod(Context context) {
  Activity activity = (Activity) context;
  // do stuff with the activity
}
```
We could probably allow using `Activity` as the method parameter instead, since it's already possible today.
