### ISSUE TITLE
Parsing a Uri containing "&"

### ISSUE THREAD

**Issue by ayushkhare** [airbnb/DeepLinkDispatch#194]
I have a url like **https://www.foo.com/category/brow-&-lash**

But,
**DeepLinkEntry entry = loader.parseUri(uriString);** 
always returns null

Is there a workaround for this?

**Comment by NurseyitTursunkulov** [comment]
you should change "&" to %26

**Comment by felipecsl** [comment]
As already stated, just URL-escape it
