### ISSUE TITLE
Retrofit style API for parsing extras

### ISSUE THREAD

**Issue by bangarharshit** [airbnb/DeepLinkDispatch#208]
Retrofit has an API:
```java
@GET("group/{id}/users")
Call<List<User>> groupList(@Path("id") int groupId);
```

A similar API for parsing parameter is:
```java
  @DeepLink("dld://methodDeepLink/{param1}/")
  public static Intent intentForDeepLinkMethod(Context context, @Path("param1") String param1) {
    return new Intent(context, MainActivity.class).setAction(ACTION_DEEP_LINK_METHOD);
  }
```
The advantage of using this approach:
1. The compiler knows the type of param1 in a bundle and so we can add PreConditions.
2. Stricter check on param1. Currently, if param1 is renamed to param2 it fails at runtime. In the new case, the build fails. 

While the system can be extended to arbitrary types with the help of deserializers and Preconditions, it is best suited for primitives

**Comment by okarakose** [comment]
Any progress on this ?

**Comment by bangarharshit** [comment]
I had a version locally but never sent a PR. I wanted to gauge interest before contributing to it. Closing it.
