### ISSUE TITLE
Support for AndroidX

### ISSUE THREAD

**Issue by forkch** [airbnb/DeepLinkDispatch#222]
We use your library in our app. Any plans to migrate it to AndroidX? 
Some of the generated code contains references to the old support library package structure.

**Comment by iam1492** [comment]
+1 same with me

**Comment by tallnato** [comment]
I think there is already support for that, if you check the last commit in master.

They just need to release it 🙏

**Comment by rossbacher** [comment]
AndroidX support is merged on master. Please build the lib and give it a spin. We were not able to fully test all of the new changes here yet and I'm a bit hesitant to release it without having done so.

**Comment by rossbacher** [comment]
And please leave feedback about it here, either if it all works or if you found issues with it, the more we know the quicker we can release it with AndroidX support. Also thx to @carvaq for creating the AndroidX PR!

**Comment by bblia** [comment]
i'm getting a failed build because it can't find the class for this import in DeepLinkDelegate.java:

```
import androidx.core.content.LocalBroadcastManager;
                            ^
  symbol:   class LocalBroadcastManager
  location: package androidx.core.content
```

it looks like it needs to be `import androidx.localbroadcastmanager.content.LocalBroadcastManager`

**Comment by rogerhu** [comment]
Here is a breaking bug report for Google: https://issuetracker.google.com/issues/116745353

The workaround is to use https://github.com/airbnb/DeepLinkDispatch/pull/230.

**Comment by anjalsan** [comment]
@rogerhu What is the workaround for AndroidX?

**Comment by rogerhu** [comment]
Until this library is released and/or this PR (https://github.com/airbnb/DeepLinkDispatch/pull/230) is merged, you can use JitPack.io with my forked branch:

```
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

Then add:

```
dependencies {
  implementation "com.github.rogerhu.DeepLinkDispatch:deeplinkdispatch:maven-SNAPSHOT"
  annotationProcessor "com.github.rogerhu.DeepLinkDispatch:deeplinkdispatch-processor:maven-SNAPSHOT"
}
```

**Comment by ron-steiner** [comment]
Hi there
using 3.1.1, I can see that #230 is merged and the generated `DeepLinkDelegate` class (DeepLinkDelegate.java) still imports

`import androidx.core.content.LocalBroadcastManager;` 

when it should be 
`import androidx.localbroadcastmanager.content.LocalBroadcastManager;`

major blockage for us as we migrate to AndroidX.

Any advice?

**Comment by diegoescudero** [comment]
@ron-steiner 
Seeing the same issue here as well, even with PR 230 merged. Will update if I find anything useful.

**Comment by rogerhu** [comment]
It hasn't been released yet.  Use https://github.com/airbnb/DeepLinkDispatch/issues/222#issuecomment-427938402 to test.

**Comment by radityagumay** [comment]
https://github.com/airbnb/DeepLinkDispatch/issues/222#issuecomment-427938402 did the trick. Thanks

**Comment by radityagumay** [comment]
@rogerhu did not work for me.

@diegoescudero do you solve this issue?

**Comment by radityagumay** [comment]
@ron-steiner https://github.com/airbnb/DeepLinkDispatch/issues/222#issuecomment-444768093 i got the same. didnt work also for me.

@diegoescudero any update?

**Comment by rogerhu** [comment]
Use this instead:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

```

And your build.gradle:

```
    implementation "com.github.airbnb.DeepLinkDispatch:deeplinkdispatch:-SNAPSHOT"
    annotationProcessor "com.github.airbnb.DeepLinkDispatch:deeplinkdispatch-processor:-SNAPSHOT"
```

**Comment by diegoescudero** [comment]
@radityagumay 

I ended up using a specific commit, because I want predictable builds.

```
implementation "com.github.airbnb.DeepLinkDispatch:deeplinkdispatch:eb7e520d87"
kapt "com.github.airbnb.DeepLinkDispatch:deeplinkdispatch-processor:eb7e520d87"
```

**Comment by radityagumay** [comment]
@rogerhu thanks man it works https://github.com/airbnb/DeepLinkDispatch/issues/222#issuecomment-449757686

**Comment by rossbacher** [comment]
Fixed with release of 4.0.0: https://github.com/airbnb/DeepLinkDispatch/releases/tag/4.0.0

**Comment by ron-steiner** [comment]
Super-good news :) thanks!

**Comment by bblia** [comment]
https://github.com/airbnb/DeepLinkDispatch/issues/243
