### ISSUE TITLE
Consider making the Callbacks more loosely coupled

### ISSUE THREAD

**Issue by mbarany** [airbnb/DeepLinkDispatch#23]
Right now the only way to take advantage of the Callbacks is to implement the interface in your Application. Consider instead using an Intent with a specific signature that could be implemented in a Broadcast Receiver.

**Comment by felipecsl** [comment]
That's a great point and is something we've talked about in the past. We definitely want to improve it. An intent could be a good idea. Thanks for your input!

**Comment by cdeonier** [comment]
Your idea sounds a lot cleaner, so we added this enhancement.
