### ISSUE TITLE
Better generated documentation format

### ISSUE THREAD

**Issue by alexfu** [airbnb/DeepLinkDispatch#236]
The generated documentation (`deeplink.txt`) is far from readable. Is it markdown? Any markdown parser I've used, spits out the same ugly text with actual newline characters (`\n`) instead of a new line. 

Here is an example output after giving it to a markdown parser:

<img width="750" alt="screen shot 2018-12-20 at 10 25 56 am" src="https://user-images.githubusercontent.com/987398/50293494-b9e9bf80-0441-11e9-9caf-9f7ad6e412a0.png">

The output is `.txt` so, is it plain text? I don't understand the `|#|` parts either. The documentation generator is very valuable but the output of the file negates all that.

**Comment by Hank-Leafly** [comment]
Seconded. The generated doc is virtually unreadable.

**Comment by felipecsl** [comment]
I agree. This should be addressed by #213 though

**Comment by rossbacher** [comment]
Closing after #246 is merged.
