### ISSUE TITLE
Problem Restarting Intent with Instrumental Testing

### ISSUE THREAD

**Issue by minUswachoke** [airbnb/DeepLinkDispatch#252]
Having trouble performing instrumental Testing on this deeplink libs. It seem each test scenario  doesnt kill the application after performing the test. For example ATest.kt contain three test scenario. Each test login the user, however the user is still login after the first test. Causing an error to other test scenario.

**Comment by felipecsl** [comment]
Questions are better suited Q&A websites like stackoverflow.com
Please keep this issue tracker for bugs and features only 😄 thanks!
