### ISSUE TITLE
To get Deeplink path String without host name 

### ISSUE THREAD

**Issue by kraghu** [airbnb/DeepLinkDispatch#253]
Hi there,
Is there a way to get just current  path name out of the deep link url without host name ? I don't wanna use string manipulation . For example , 
```
airbnb://help 
https://airbnb.com/help 

```
Is there a way to just get the  path name **/help** without the **airbnb://**  or **https://airbnb.com**? we already annotate **_/help_** as `weblink` and `applink` right now on the activity class. Right now am using String manipulation to check the path as below .
```
String deepLinkUrl = intent.getStringExtra(DeepLink.URI);
 if (deepLinkUrl.contains("/help")) {
            do some thing 
        }
```
Please point me in the right direction I might be missing something.

**Comment by kraghu** [comment]
@schleyfox @mcharkov any idea ?

**Comment by felipecsl** [comment]
You can use `java.net.URL` to parse the String into an URL object and then call `getPath()` on it.
