### ISSUE TITLE
this library what to do

### ISSUE THREAD

**Issue by linhou** [airbnb/DeepLinkDispatch#254]
@DeepLink("foo://example.com/methodDeepLink/{param1}")
public static Intent intentForDeepLinkMethod(Context context) {
  return new Intent(context, MainActivity.class)
      .setAction(ACTION_DEEP_LINK_METHOD);
}

this ，  I know I want to startActivity is MainActivity  ，I don't know  this code  want to express mean？？？？

**Comment by felipecsl** [comment]
Please provide a meaningful explanation of the issue you're having and how to reproduce it.
Questions are better suited for stackoverflow.com
