### ISSUE TITLE
Support dynamic feature modules

### ISSUE THREAD

**Issue by MohamedElidrissi** [airbnb/DeepLinkDispatch#255]
Currently there's no way to use DeepLinkDispatch in a modularized Android project where we have multiple feature modules since if we have our `@DeepLinkHandler` Activity in the base module and we want to add a `@DeepLinkModule` annotated class that resides in a feature module we can't as the base module doesn't depend on the feature modules.
if there is a workaround for this feel free to close this issue

**Comment by MohamedElidrissi** [comment]
Since nobody seems to care about this, I dug into DLD and I found a way to workaround this by making a `CustomDeepLinkDelegate` class that accepts a `List<? extends Parser>`  directly, this makes it possible do use dependency injection to pass a `List` of `*DeepLinkLoader` classes instead of depending on the generated `DeepLinkDelegate` that forces the use of the `@DeepLinkHandler` thus making it impossible to add loaders dynamically (I'm yet to test this with feature modules, hopefully it works well 🤞)

**Comment by MohamedElidrissi** [comment]
After trying out the above it does work fine, however looking at all the boilerplate and reflection this not something I'd consider for a production app., so this issue remains open
![Annotation 2019-06-07 174529](https://user-images.githubusercontent.com/45264848/59123136-14250100-894c-11e9-8dad-fa37b2dede9d.png)

![Annotation 2019-06-07 174735](https://user-images.githubusercontent.com/45264848/59123269-6534f500-894c-11e9-8a68-c0eb855ac070.png)

**Comment by leanh215** [comment]
Facing same issue. Waiting for someone come to rescue

**Comment by leanh215** [comment]
Basically use reflection to get Loader and add to a `BaseDeepLinkDelegate` is not big issue. I tested with below code and it worked well
`@DeepLinkHandler(AppDeepLinkModule::class)
class DeepLinkActivity : Activity() {

    companion object {
        const val DYNAMIC_DEEPLINK_LOADER = "com.vingroup.vinid.dynamicfeature.deeplink.DynamicDeepLinkModuleLoader"
        const val DYNAMIC_DEEPLINK_LOADER_NOT_EXIST = "com.vingroup.vinid.dynamicfeature.deeplink.DynamicDeepLinkModuleLoaderXXX"
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val delegate = BaseDeepLinkDelegate(
            listOfNotNull(
                AppDeepLinkModuleLoader(),
                loadDeepLinkLoader(DYNAMIC_DEEPLINK_LOADER),
                loadDeepLinkLoader(DYNAMIC_DEEPLINK_LOADER_NOT_EXIST)
            )
        )
        delegate.dispatchFrom(this)
        finish()
    }

    private fun loadDeepLinkLoader(loadClassName: String): Parser? {
        return try {
            Class.forName(loadClassName).newInstance() as Parser
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
}`
