### ISSUE TITLE
build failed in version 4.1.0 with kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by mrnorouzi** [airbnb/DeepLinkDispatch#258]
When I update version from 3.1.1 to 4.1.0 for supporting androidx, the build failed with the following exception:
```
> Task :app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> kotlin.KotlinNullPointerException (no error message)
```

code of my project is **java**. It hasn't been written by kotlin

**Comment by nigelkeirross** [comment]
Hi, I know this is closed, but  I have exactly the same issue with a project entirely in java, but I get the same error message when command line building (on linux) with gradlew
Can you tell me how you solved it? Thanks

**Comment by rossbacher** [comment]
@nigelkeirross this is on master? Or which version are you using? Can you provide the full stacktrace of the error? (You can do that when building with gradle by adding `--stacktrace` to the command.

**Comment by nigelkeirross** [comment]
Hi
It has nothing to do with Airbnb, it is another project (xDrip-plus) that I
am trying to build. It has no Kotlin at all, and when I googles the error,
your project came up.
This is why I was trying to see how it was solved.
Thanks
Nigel

**Comment by rossbacher** [comment]
@nigelkeirross So you are not using deeplinkdispatch in that project? If not most likely this is not the same error. 

Still you would need t get the full stack trace.
