### ISSUE TITLE
Documentation: AppDeepLinkModuleLoader instead of AppDeepLinkModuleRegistry

### ISSUE THREAD

**Issue by igorkovalchuk** [airbnb/DeepLinkDispatch#278]
DeepLinkDispatch version: 4.1.0 

Today in the [documentation](https://github.com/airbnb/DeepLinkDispatch) you have:

```
/** This will generate a AppDeepLinkModuleRegistry class */
@DeepLinkModule
public class AppDeepLinkModule {
}
```

I was confused because I got a compilation error here:

```
DeepLinkDelegate deepLinkDelegate = 
        new DeepLinkDelegate(new AppDeepLinkModuleRegistry());
```
It can't find the AppDeepLinkModuleRegistry.
I've discovered that I should use a AppDeepLinkModuleLoader (generated class) instead.
Do you have a mistype in the documentation?

Thank you!

**Comment by rossbacher** [comment]
Possibly it should all be Registries now as we renamed that and made the naming moire clear in 4.0.
Let me check that on Monday and fix if necessary.

**Comment by rossbacher** [comment]
Also are you sure you are using 4.x of both dependencies the lib and the processor? If you mix them that could also happen.

**Comment by rossbacher** [comment]
I did check and we don't have any `Loader` code left over. (e.g. see our own sample https://github.com/airbnb/DeepLinkDispatch/blob/master/sample/src/main/java/com/airbnb/deeplinkdispatch/sample/DeepLinkActivity.java#L18).

I'm closing this as you must be using old and or mixed dependencies.

**Comment by rossbacher** [comment]
Sorry when I said 4.x I meant 5.x.
