### ISSUE TITLE
cannot find symbol:  symbol:   class SampleModuleLoader

### ISSUE THREAD

**Issue by ismaielsharif** [airbnb/DeepLinkDispatch#279]
**cannot find symbol**
        DeepLinkDelegate deepLinkDelegate = new DeepLinkDelegate(new SampleModuleLoader(), new LibraryDeepLinkModuleLoader());
                                                                     ^
  **symbol:   class SampleModuleLoader**
  location: class DeepLinkActivity

import com.airbnb.deeplinkdispatch.DeepLinkHandler;

@DeepLinkHandler({SampleModule.class, LibraryDeepLinkModule.class})
public class DeepLinkActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        DeepLinkDelegate deepLinkDelegate = new DeepLinkDelegate(new **SampleModuleLoader(), new LibraryDeepLinkModuleLoader()**);
        deepLinkDelegate.dispatchFrom(this);
        finish();
    }
}

after generating DeepLinkDelegate successfully. I'm unable to generate SampleModuleLoader() class. using 5.1.0 lib.

**Comment by linnar** [comment]
The generated classes now end with Registry instead of Loader, so you should import and use  SampleModuleRegistry and LibraryDeepLinkModuleRegistry. I think this should be noted in documentation, I was also confused.

**Comment by rossbacher** [comment]
the documentation was updated. Can you link me to the part that is confusing?

**Comment by linnar** [comment]
The documentation is good for new users and the place where I noticed the change, but I think it would be nice to have a mention of the renaming in the changelog or section for upgrading 4.x to 5.x in the readme.

**Comment by rossbacher** [comment]
https://github.com/airbnb/DeepLinkDispatch/pull/281

**Comment by ismaielsharif** [comment]
> The generated classes now end with Registry instead of Loader, so you should import and use SampleModuleRegistry and LibraryDeepLinkModuleRegistry. I think this should be noted in documentation, I was also confused.

Thanks man. i have already used an alternate way for DeppLinking.
