### ISSUE TITLE
@DeepLinks stopped working

### ISSUE THREAD

**Issue by joluet** [airbnb/DeepLinkDispatch#28]
I discovered an issue with the `@DeepLinks` annotation in version 1.2.0. When using a single link with `@DeepLink` it works fine but as soon as I use `@DeepLinks` with multiple URIs it stops working and the `DeepLinkLoader.java` class is not generated anymore. Also, calling `./gradlew --stop` and doing a clean build doesn't fix it.

**Comment by Denvar** [comment]
I mention this issue on this comment on a closed ticket
https://github.com/airbnb/DeepLinkDispatch/issues/24#issuecomment-121001662

**Comment by felipecsl** [comment]
I'm closing this one and reopening the other one since that has code snippets
