### ISSUE TITLE
Not supported valid URIs for deeplinks with same path and different number of parameters

### ISSUE THREAD

**Issue by cvillaseca** [airbnb/DeepLinkDispatch#303]
Hi,

Since we updated the  library to version 5.X some deeplinks like `myapp://vehicle/{vehicleId}` have stopped working. The problem is that with the new version it doesn’t handle multiple links with the same structure, it only handles the first one is created in the registry class. For example:

``` java
public final class MyDeepLinkModuleRegistry extends BaseRegistry {
  public MyDeepLinkModuleRegistry() {
    super(Collections.unmodifiableList(Arrays.<DeepLinkEntry>asList(
      new DeepLinkEntry("myapp://vehicle/{make}/{model}", DeepLinkEntry.Type.METHOD, VehicleDetailNavigation.class, "newIntentForTaskStackBuilderMethods"),
      new DeepLinkEntry("myapp://vehicle/{vehicleId}", DeepLinkEntry.Type.METHOD, VehicleDetailNavigation.class, "newIntentForTaskStackBuilderMethods")
    )), Utils.readMatchIndexFromStrings( new String[] {matchIndex0(), }),
    new HashSet<String>(Arrays.<String>asList()));
  }
}
```

This is considered a valid deeplink

```
myapp://vehicle/vw/golf
```

But this deeplink won’t be valid. You can check this by using `DeepLinkDelegate.supportsUri("myapp://vehicle/123")`

```
myapp://vehicle/123
```

This was working in version 4.X but with version 5.X it's not.

Thank you 🙏

**Comment by rossbacher** [comment]
I'll have a look at that. I don't think we have a test case for this and thus it might have been missed.

**Comment by stari4ek** [comment]
There is a chance that incremental build is involved.
I had same issue. Bunch of "foo://navigate/*" declared, but only one was added to registry.
Forcing rebuild the project solved the issue

**Comment by rossbacher** [comment]
Sorry it took that long but this is fixed now and in release https://github.com/airbnb/DeepLinkDispatch/releases/tag/5.3.0.

**Comment by cvillaseca** [comment]
Thank you for the fix @rossbacher 🙏
