### ISSUE TITLE
How to use @DeepLink only with scheme specified (or maybe to specify default activity)

### ISSUE THREAD

**Issue by bakua** [airbnb/DeepLinkDispatch#32]
Hello, thank you for this library. I'd like to ask if it is possible to use it with scheme only. What I am trying to achieve is to catch everything that is myscheme:// and point it to my MainActivity. But since URL specified with annotation requires some host, it is not possible.

My question is, is there any way how to do @DeepLink("myscheme://")?

Thank you

**Comment by felipecsl** [comment]
This is not currently possible and since you don't have any type of compicated parameters or different URIs for different activities, you might be better off just using a plain `intent-filter` and not using this lib at all.

**Comment by bakua** [comment]
Thanks for response. I don't have any complicated parameters at the moment, but i will. I guess I'll watch for 	onError(DeepLinkError error) and just launch MainActivity there.
