### ISSUE TITLE
Add deferred deep linking component

### ISSUE THREAD

**Issue by aaustin** [airbnb/DeepLinkDispatch#41]
Hey team. Good stuff with this library! 

What would you say if I added [Branch](https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK) as an optional component to call the dispatch on install if the user originated from a deep link? That way, folks can choose to add in a post-install deep linking component if they so choose. 

I can it to the sample project and add some simple instructions on calling the dispatch directly. Plus, with Branch, they can create hosted URLs with custom deep link paths to complete the full circle integration from link -> dispatch.

Give me :+1: to proceed and I'll make PR or let me know your thoughts.

**Comment by cdeonier** [comment]
Deferred deep linking is something we're thinking about, but supporting multiple vendors for campaigns/referral tracking is beyond the scope of this library right now. We're going to keep this library lightweight and stick to direct deep links until we have a generalized approach for deferred deep links.
