### ISSUE TITLE
Reading params collection

### ISSUE THREAD

**Issue by jczerski** [airbnb/DeepLinkDispatch#42]
Library works fine with multiply params in URI? 
 ``` example://example.com/deepLink?param1=123&param2=456&param3=789 ``` ? 
Right now I can get only first parameter.

Best regards,
Jack

**Comment by jczerski** [comment]
Sorry for my mistake. Everything is ok. My terminal escapes "&" char.
My fault.

Sorry one more time.

**Comment by felipecsl** [comment]
no worries :)
