### ISSUE TITLE
Proguard rule for annotated methods

### ISSUE THREAD

**Issue by jczerski** [airbnb/DeepLinkDispatch#44]
Hi,

I would like to ask you about proguard rule for annotated methods, which prepare intents.
``` 
-keepclasseswithmembers class * {
     public static android.content.Intent *(android.content.Context);
} 
``` 
works, but I would like to do it better using something similar to: 
```
-keepclasseswithmembers class * {
     @com.airbnb.deeplinkdispatch.DeepLink <methods>;
} 
``` 
but it does not work - proguard removes unused methods.

What do I wrong?

Thank you in advance for answer and great library.

Best regards,
Jack

**Comment by felipecsl** [comment]
can you try with `-keep class com.airbnb.deeplinkdispatch.** { *;}` ?

**Comment by jczerski** [comment]
```
-keep class com.airbnb.deeplinkdispatch.** { *; }
-keepclasseswithmembers class * {
     @com.airbnb.deeplinkdispatch.DeepLink <methods>;
}
```
Thank you, it works as I expect.

To my mind it would be nice if you put it to wiki.

Best regards,
Jack

**Comment by felipecsl** [comment]
thank you! I'll add them

**Comment by mtiidla** [comment]
Could you please also add a reminder to configure additional Proguard rules when using custom annotations like AppDeepLink and WebDeepLink. We were just burned, so maybe could prevent others from making the same mistake :)

**Comment by felipecsl** [comment]
@mtiidla do you mind contributing a quick PR?

**Comment by mtiidla** [comment]
Sure, I will try over the weekend.
