### ISSUE TITLE
Issue with Multi Dex Enabled

### ISSUE THREAD

**Issue by stripathi669** [airbnb/DeepLinkDispatch#48]
Hi

So I tried and tested the library for my android app. Everything worked fine. Then I had to enable multi dex due to 65K limit.

Now the deeplink won't open the target activity. Instead I would only see this in the console:

     I/MultiDex﹕ VM with version 2.1.0 has multidex support
     I/MultiDex﹕ install
     I/MultiDex﹕ VM has multidex support, MultiDex support library is disabled.

As a result, the app won't open at all.

**Comment by felipecsl** [comment]
We use DeepLinkDispatch in an app that has multidex enabled and it works fine. This log output you included doens't seem related to this library specifically, it is an Android log. Do you have any stack trace?

**Comment by stripathi669** [comment]
Hi. You are correct.

I was using  two different scheme in the manifest (two data tags). And the app wasn't opening. There is no Dex Issue.

Is there a way to use multiple scheme instead of just one?

Sorry for opening this false issue. Should I close it or open a new one this the above query.

**Comment by felipecsl** [comment]
yeah you can, the sample app does exactly that. Check the AndroidManifest for an example!

**Comment by felipecsl** [comment]
https://github.com/airbnb/DeepLinkDispatch/blob/master/sample/src/main/AndroidManifest.xml

**Comment by stripathi669** [comment]
That is weird. For me somehow, if mention two schema, none of them seem to work. App just blinks and exits without any trace-stack.

My manifest looks like this:

           <activity
            android:name="com.airbnb.deeplinkdispatch.DeepLinkActivity"
            android:theme="@android:style/Theme.NoDisplay">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="http" />
                <data android:scheme="fluttr" />
                
                    
                    
            </intent-filter>
        </activity>

My decorator looks like this:

       @DeepLinks({"fluttr://getfluttr.com/flap/{id}/{slug}/", "http://getfluttr.com/flap/{id}/{slug}"})

Few other options:

   1. If the app is in the background, It comes to foreground. No relation to dispatched link whatsoever.
   2. If I comment out http, other schema is working just fine.

**Comment by felipecsl** [comment]
have you tried with the latest snapshot version `1.4.0-SNAPSHOT`?
