### ISSUE TITLE
URL schemes with a number in them are seen as malformed

### ISSUE THREAD

**Issue by ronocod** [airbnb/DeepLinkDispatch#49]
Using a deep link with a scheme of `jackson5://` will cause a compilation error

**Comment by felipecsl** [comment]
looks like OkHttp's `HttpUrl` doens't allow digits in the scheme part of the URL. I'll look into patching it

**Comment by felipecsl** [comment]
Fixed in https://github.com/square/okhttp/pull/1849. Will update `DeepLinkUrl` once that is merged
