### ISSUE TITLE
Not prepared to handle parameters as "host"

### ISSUE THREAD

**Issue by MichaelEvans** [airbnb/DeepLinkDispatch#53]
DLD seems to assume that all templating happens on "path parameters", and never on the "host". (i.e. `airbnb://foo/{bar}` is valid, but `airbnb://{bar}` is not.)

Is this expected functionality (I don't think it's documented)? If not, I can try to put up a PR for the change.

**Comment by MichaelEvans** [comment]
Fix put up in #54

**Comment by felipecsl** [comment]
it was expected, but not documented. thanks for the PR!
