### ISSUE TITLE
sample project is not working

### ISSUE THREAD

**Issue by sphdigital** [airbnb/DeepLinkDispatch#67]
missing DeepLinkActivity in the sample project

**Comment by MichaelEvans** [comment]
That file is generated by the annotation processor. Did you build the project?

**Comment by sphdigital** [comment]
I had build the project but the build is failed? can you guide me how you build the project?

**Comment by felipecsl** [comment]
`./gradlew clean assemble` should do it!

**Comment by sphdigital** [comment]
thanks its working now

**Comment by thuytrinh** [comment]
It's totally worth mentioning this in the Usage section of the README. Otherwise, one might get stuck for like 15 minutes before heading down to the Issues page to figure out. That's hassle!

**Comment by felipecsl** [comment]
pull requests welcome
