### ISSUE TITLE
Introduce a way to determine which path was used when multiple paths are used with @DeepLinks()

### ISSUE THREAD

**Issue by MichaelEvans** [airbnb/DeepLinkDispatch#7]
Right now if you use something like `@DeepLinks({"example.com/deepLink/{id}", "example.com/anotherDeepLink"})`, you can determine which link was used by the presence of `id`. But if you did something like `@DeepLinks({"example.com/deepLink", "example.com/anotherDeepLink"})`, you'd have no mechanism to determine which path was used to get here.

**Comment by felipecsl** [comment]
it looks like one possible solution would be to expose in the intent extas the original URI string used for matching, eg.: `"example.com/deepLink/{id}"` or `"example.com/anotherDeepLink"` in this case.
