### ISSUE TITLE
Issues with deeplinks in the Sample app

### ISSUE THREAD

**Issue by scottyab** [airbnb/DeepLinkDispatch#72]
Testing the sample app and finding some of the deep link are not resolving. I believe I am using the correct adb cmds and deeplinks defined in the sample? but I'd appreciate second pair of eyes.  

The following work a-ok :)
```
adb shell am start -W -a android.intent.action.VIEW -d "dld://example.com/deepLink" com.airbnb.deeplinkdispatch.sample
adb shell am start -W -a android.intent.action.VIEW -d "http://example.com/fooScott" com.airbnb.deeplinkdispatch.sample

```
However these don't resolve intent  :( 
```
adb shell am start -W -a android.intent.action.VIEW -d "dld://classDeepLink?qp=123" com.airbnb.deeplinkdispatch.sample
adb shell am start -W -a android.intent.action.VIEW -d "dtd://host/somePath/54321" com.airbnb.deeplinkdispatch.sample
adb shell am start -W -a android.intent.action.VIEW -d "dld://classDeepLink" com.airbnb.deeplinkdispatch.sample
adb shell am start -W -a android.intent.action.VIEW -d "dld://methodDeepLink/abc123" com.airbnb.deeplinkdispatch.sample
adb shell am start -W -a android.intent.action.VIEW -d "dtd://example.com/deepLink/scottid123" com.airbnb.deeplinkdispatch.sample
```

I then wondered if it's because I had the action wrong, but adding the defined actions doesn't seem to help either. 

```
adb shell am start -W -a deep_link_complex -d "dtd://host/somePath/54321" com.airbnb.deeplinkdispatch.sample
adb shell am start -W -a deep_link_method -d "dld://methodDeepLink/scottsparam" com.airbnb.deeplinkdispatch.sample
```

To confirm this is what I'm seeing output from adb 
```
macbook:~ user$ adb shell am start -W -a android.intent.action.VIEW -d "dld://classDeepLink?qp=123" com.airbnb.deeplinkdispatch.sample
Starting: Intent { act=android.intent.action.VIEW dat=dld://classDeepLink?qp=123 pkg=com.airbnb.deeplinkdispatch.sample }
Error: Activity not started, unable to resolve Intent { act=android.intent.action.VIEW dat=dld://classDeepLink?qp=123 flg=0x10000000 pkg=com.airbnb.deeplinkdispatch.sample }
```

**Comment by felipecsl** [comment]
I've had problems with `adb shell am` in the past, so what I usually do is:

```
adb shell
am start -a android.intent.action.VIEW -d "schema://host/path"
```
What was happening to me was that `adb shell am start` was not sending the entire URI for some weird reason. Opening a shell prompt works fine.
Also you don't need to specify the package after the URI.
I don't think there's a bug here but please feel free to reopen if you think so. Also please include your `@DeepLink` annotation to help debug the problem.

**Comment by scottyab** [comment]
arh yes, that's it. Running `am` cmd from inside adb shell works as expected. Oh btw I didn't include the `@DeepLink` annotations as these are the ones form your sample. I'll ping over a PR with updated readme as think it'll help others when testing the viability of this library.

**Comment by felipecsl** [comment]
nice :+1: thanks!
