### ISSUE TITLE
Possible Issues with Google App Indexing Api

### ISSUE THREAD

**Issue by stripathi669** [airbnb/DeepLinkDispatch#74]
Hi,

I have implemented deep link dispatch, and deep links seem to be working fine. However, there are issues with Fetch as google bot for android apps. (Link: https://support.google.com/webmasters/answer/6178089?hl=en)

Specifically, it says that the URI is unsupported. Same Uri is working perfectly fine, otherwise.
Do you think it has something to do with this library?

**Comment by MinceMan** [comment]
We're using this with app indexing and don't seem to have any problems with it.

**Comment by felipecsl** [comment]
We're using app indexing as well, no problems so far. I'm assuming it's not an issue with DLD, but feel free to reopen if you find a bug.
