### ISSUE TITLE
DeepLink.IS_DEEP_LINK always equals false

### ISSUE THREAD

**Issue by qbait** [airbnb/DeepLinkDispatch#81]
getIntent().getBooleanExtra(DeepLink.IS_DEEP_LINK, false) returns always false, even when I open app from deeplink.

My annotation looks like `@DeepLink("myapp://open")`

My command to open deeplink `am start -W -a android.intent.action.VIEW -d "myapp://open"`

**Comment by felipecsl** [comment]
@qbait can you share a test project that reproduces the error? We have a unit test that checks for that flag on `MainActivityTest.testIntent()` so I'd be surprised if it's actually a bug

**Comment by felipecsl** [comment]
Most likely your intent is not coming through DeepLinkDispatch but through another mechanism, maybe regular android intent.

**Comment by qbait** [comment]
@felipecsl I created project from the scratch with the same result (DeepLink.IS_DEEP_LINK always equals false). It's the standard android project with DeeplinkDispatch, available at my github https://github.com/qbait/DeeplinkDispatchTest

**Comment by firasalkafri** [comment]
Facing the same problem

**Comment by ndlovucn** [comment]
Hi has anybody found a way around this bug?

**Comment by firasalkafri** [comment]
@ndlovucn can you copy paste your Manifest?

**Comment by ndlovucn** [comment]
<activity
            android:name=".ui.home.HomeActivity"
            android:label="@string/app_name"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="@string/app_scheme" />
            </intent-filter>
        </activity>

**Comment by firasalkafri** [comment]
No, you should have this activity defined:

```
        <activity
            android:name="com.airbnb.deeplinkdispatch.DeepLinkActivity"
            android:theme="@android:style/Theme.NoDisplay">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host=**"EXAMPLE.COM"**
                    android:scheme="**http**" />
            </intent-filter>
        </activity>
```

**Comment by ndlovucn** [comment]
ok I see, will update and test, thank you for your prompt response

**Comment by felipecsl** [comment]
Has this been resolved?

**Comment by felipecsl** [comment]
I assume this has been resolved. If you look into `DeepLinkActivity` (for v1.5) or `DeepLinkDelegate` (for v2 - https://github.com/airbnb/DeepLinkDispatch/blob/master/deeplinkdispatch-processor/src/test/resources/DeepLinkDelegate.java#L74), you'll see that this boolean flag is being set to true there. If you're seeing `false`, most likely your Intent hasn't gone through DeepLinkDispatch at all

**Comment by willem-h** [comment]
How can I make sure my Intent is being passed through DeepLinkDispatch?

**Comment by felipecsl** [comment]
@willem-h is this question related to the original issue?
Anyways, answering your question, when you receive the Intent, you can verify whether or not it has been handled by DeepLinkDispatch by doing something like `intent.getBooleanExtra(DeepLink.IS_DEEP_LINK, false)`. If this returns `true`, then it was passed through DeepLinkDispatch
