### ISSUE TITLE
Method Annotations and getting parameter values

### ISSUE THREAD

**Issue by jam0cam** [airbnb/DeepLinkDispatch#85]
As with the example here, is there a way to fetch out the "param1" value, so that I can put it in the Intent as an extra with my own key/value pair? 

```
@DeepLink("foo://example.com/methodDeepLink/{param1}")
public static Intent intentForDeepLinkMethod(Context context) {
  return new Intent(context, MainActivity.class).setAction(ACTION_DEEP_LINK_METHOD);
}
```

Thanks,
Jia

**Comment by jam0cam** [comment]
I can just change "param1" to whatever parameter name that I want to be in the bundle

**Comment by johnryan** [comment]
@jam0cam how did you get this working? i.e. where did you get the bundle from in this example?

**Comment by felipecsl** [comment]
@johnryan starting with version `3.0.0-rc1` you can add an additional `Bundle` parameter to methods in order to catch the extras

**Comment by johnryan** [comment]
@felipecsl is there any documentation for 3.0.0-rc1? Seems like the setup is substantially different...i.e. no DeepLinkActivity etc. Do you have to change the manifest to use a receiver instead?

**Comment by felipecsl** [comment]
@johnryan I'm gonna update the README today to reflect v3, since that's still the v2 instructions. sorry for the delay!

**Comment by felipecsl** [comment]
@johnryan in the meantime you can look into the sample project code.
