### ISSUE TITLE
Proposal: Make generated DeepLinkActivity optional

### ISSUE THREAD

**Issue by hzsweers** [airbnb/DeepLinkDispatch#86]
## The problem

Currently, all deeplink handling is done in a generated `DeepLinkActivity` that you must add to your manifest. While this is a convenient mechanism for easy dropping in, it's not very extensible if you have any requirements around your deeplinking. In particular, you ultimately don't control the entry point to your app, and can't run any sort of preconditions. 

## Example

Any app that has required login to proceed faces this issue. You receive a deeplink, check if the user is logged in, if yes then proceed, otherwise take them to the login screen. Unfortunately this doesn't allow for that kind of handling since there's no control over the generated activity. The dispatch gets done, regardless of the app state. 

## Proposed solutions

The generated `DeepLinkActivity` is actually well-suited to extraction to a class. My proposal is this: generate a `Dispatcher` class like the following:

```java
public final class Dispatcher {
    public static DispatchResult dispatchFrom(Activity activity) {
        // Check activity != null...
        // Do all the dispatch handling...

        // Return the result
        return new DispatchResult(isError, uri, errorMessage);
    }
}
```

Where `DispatchResult` is a simple data class representing the information you'd otherwise send to the `DeepLinkReceiver`.

This would allow you to take advantage of the main benefit of the library (generated uri handling) while allowing you to keep control over entry points.

```java
public class LaunchActivity extends Activity {
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        if (isDeepLink() && requiredConditionsAreValid() && isLoggedIn()) {
            DispatchResult result = Dispatcher.dispatchFrom(this);

            if (!result.isSuccessful()) {
                // Do something about it
            else {
                // Done? Maybe? ¯\_(ツ)_/¯
                return;
            }
        }
    }
}
```

You could keep the currently existing implementation as well for convenience and just have it call through  to the `Dispatcher`. This would also make it easy to test, especially if you opted for a new instance vs. static methods (which opens up easy injection and handling via Dagger/other DI implementations).

The alternative idea would be to add some form of precondition callback that the developer could register. This isn't as ideal though since it's fairly limited.

Names are totally up for discussion by the way! Curious to hear people's thoughts on this. If it's something you'd be for, can gladly contribute a PR for this.

**Comment by felipecsl** [comment]
This a pretty interesting proposal. To be fair, I've never been super happy with the way you're required to have `DeepLinkActivity` in your manifest and how rigid it is. Having it be more flexible is totally fair and I believe would make for a great addition.
It seems like you got the details well spec`d out in your head already, so please feel free to contribute a PR and I'd be glad to review it!
Thanks Zac!

**Comment by cdeonier** [comment]
I agree, the use case you outlined seems pretty typical. I also like the proposal, and would be in support of a PR!

**Comment by hzsweers** [comment]
Awesome, I'll get started on that. Any opinions on namings?

**Comment by felipecsl** [comment]
None so far. We can revisit when we have something to look at
