### ISSUE TITLE
Regular Expression Symbols : Deeplink can't set value

### ISSUE THREAD

**Issue by prisa1987** [airbnb/DeepLinkDispatch#88]
For example : https://et/1/#/101

@DeepLink (https://et/{id}/#/{name}) 
 I try to getString("name")  --> I get null value

but in case   @DeepLink (https://et/{id}/{name}) 
I get correct value

Thank you so much :)

**Comment by MichaelEvans** [comment]
You're seeing this because everything after the # sign is part of the URL fragment, not part of the URL path.

**Comment by felipecsl** [comment]
Thanks @MichaelEvans
