### ISSUE TITLE
Using resource strings gives malformed url during compilation 

### ISSUE THREAD

**Issue by mrudult** [airbnb/DeepLinkDispatch#91]
Trying:
```
@DeepLink(R.string.web_frontend + "/scope/{token}")
```
gives:
```
Error:Malformed Deep Link URL 2131296410/scope/{token}
```
Is there a way I can use resource strings in the urls?
I've different resource strings depending on app flavors.

**Comment by mrudult** [comment]
Moved the strings to `Config` instead and it worked.

**Comment by ChengangFeng** [comment]
@mrudult how can I move the strings to `Config` ?
