### ISSUE TITLE
Dispatcher extension

### ISSUE THREAD

**Issue by markchristopherng** [airbnb/DeepLinkDispatch#92]
Its is possible to do the boostrap or start up work such as app initialization and authentication in a central location (in the dispatcher) so that the activity which has the deep link does not have to take care of this.

**Comment by felipecsl** [comment]
This has been implemented on #87. Just use version `2.0.0-SNAPSHOT` and the new `@DeepLinkHandler` annotation

**Comment by markchristopherng** [comment]
great thanks for that
