### ISSUE TITLE
deep link to handle production and test urls

### ISSUE THREAD

**Issue by markchristopherng** [airbnb/DeepLinkDispatch#95]
In our project we have multiple test environments (to support our myriad and varied testing requirements) together with our production environment.

The current @DeepLink annotation requires us to add a URL for every single environment:

@DeepLink({
“https://prod_env/showDetail/detail.html”,
“https://test_env1/showDetail/detail.html”,
“https://test_env2/showDetail/detail.html”,
“https://test_env3/showDetail/detail.html”,
“https://test_env4/mock1/showDetail/detail.html”,
“https://test_env5/mock2/showDetail/detail.html”})
public class MyShowDetailActivity ….

This results in all our test environment annotations appearing in production code! It’s unwieldy and we have sometimes introduced new test environments, which would require code change on every activity that support deep linking to add the new environment.

We acknowledge that the intent filters within AndroidManifest.xml also need to be wordy (one entry per test env), but are pretty much taken care of by having separate manifests: debug/AndroidManifest.xml (many intent filter entries - one for each env) and release/AndroidManifest.xml (only one intent filter entry for the prod env).

Unfortunately this @DeepLink java annotation can’t be as easily handled. We could try subclassing and annotate the debug subclass of MyShowDetailActivity for the debug build variant but that’s rather messy, just to get around the DeepLink annotation restriction.

Instead, if there was a variant of @DeepLink that matched without hostname and scheme, that would allow us to do something simple and elegant such as:

@DeepLink("/showDetail/detail.html”) // support all environments in a single hit and rely on intent filters to ensure the hostname or url prefix is correct
public class MyShowDetailActivity ….

So is it possible to enhance this library to handle this partial deep link match requirement?

**Comment by markchristopherng** [comment]
Alternatively do you support wildcards as this would solve this issue as well.

@DeepLink({
“https://*/showDetail/detail.html”})
public class MyShowDetailActivity ….

**Comment by untungs** [comment]
You could try with `@DeepLink({“https://{host}/showDetail/detail.html”})`

**Comment by markchristopherng** [comment]
thanks, i thought about that as well but didn't get around to trying it

**Comment by felipecsl** [comment]
It sounds like this has been addressed by #147
