### ISSUE TITLE
Plans for release?

### ISSUE THREAD

**Issue by bridgeri127** [airbnb/DeepLinkDispatch#98]
Hi all

I was wondering if you have any updates on release plans? I love the library, but am having trouble with user authentication using the DeepLinkActivity. Essentially, I want to be able to check if user is logged in before redirecting them to the relevant activity. I know that this was implemented in #87 and I see other places where you guys have spoken about version 1.6.0 and 2.0.0-SNAPSHOT, however when I try and update my build.gradle to use these version numbers it tells me they cannot be found. Am I missing something, or are they not yet available in Maven central? If you could let me know how to deal with this that would be great!

**Comment by felipecsl** [comment]
you can use version `2.0.0-SNAPSHOT`. 
Just add this to your root-level build.gradle file: 

```
allprojects {
  repositories {
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
  }
}
```

**Comment by bridgeri127** [comment]
Thanks a million for that @felipecsl , do you know when it will be available in a release build rather than a SNAPSHOT? Would prefer to keep SNAPSHOTs away from our releases.

**Comment by felipecsl** [comment]
@bridgeri127 you're welcome.
I've just uploaded [2.0.0](http://repo1.maven.org/maven2/com/airbnb/deeplinkdispatch/2.0.0/)
You can use it already, also see #100 for the changelog and updated readme
